=== jenisha45/web-development-/xml/11.phone.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <!-- Root element -->
<xs:element name="phone">
<xs:complexType>
<xs:sequence>
<xs:element name="title" type="xs:string"/>
<xs:element name="entries">
<xs:complexType>
<xs:sequence>
<xs:element name="entry" maxOccurs="unbounded">
<xs:complexType>
<xs:sequence>

<!-- Name -->
<xs:element name="name">
<xs:complexType>
<xs:sequence>
<xs:element name="first" type="xs:string"/>
<xs:element name="middle" type="xs:string" minOccurs="0"/>
<xs:element name="last" type="xs:string"/>
</xs:sequence>

<!-- Attribute -->
<xs:attribute name="gender" use="required">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:enumeration value="male"/>
<xs:enumeration value="female"/>
</xs:restriction>
</xs:simpleType>
</xs:attribute>
</xs:complexType>
</xs:element>

<!-- Phone -->
<xs:element name="phone" type="xs:string"/>

<!-- City optional -->
<xs:element name="city" type="xs:string" minOccurs="0"/>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== jenisha45/web-development-/xml/phone.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="phone.xsl"?>

<phone
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="11.phone.xsd">

<title>test</title>

<entries>

<entry>
<name gender="male">
<first>test</first>
<last>sdjh</last>
</name>
<phone>97458555</phone>
<city>Chitwan,kathamndu</city>
</entry>

<entry>
<name gender="female">
<first>test</first>
<middle>shdgsu</middle>
<last>zdgs</last>
</name>
<phone>478958934</phone>
<city>Chitwan,kathamndu</city>
</entry>

</entries>

</phone>
