<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books [
<!ELEMENT books (book+)>
<!ELEMENT book (name, author+, page, price)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (author_name, email)>
<!ELEMENT author_name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST book isbn CDATA #REQUIRED>
<!ATTLIST price currency (npr | usd) "npr">
]>
<books>
<book isbn="34324">
    <name> Web Technology</name>
<author>
<author_name> sdjf</author_name>
<email>sdjs@gmail.com</email>
</author>
<page>300</page>
<price currency="npr">450</price>
</book>
<book isbn="9003">
<name> HTML and CSS</name>
<author>
<author_name> sdd</author_name>
<email>sdd@gmail.com</email>
</author>
<page>250</page>
<price currency="npr">4150</price>
</book>
<book isbn="123">
<name> DSA</name>
<author>
<author_name> Dskd</author_name>
<email>dskd@gmail.com</email>
</author>
<page>344</page>
<price currency="usd">20</price>
</book>
</books>

